/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alcancia1;
import Classes.Archivo;
import Classes.ConchinitoDigital;
import Classes.Usuario;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
/**
 *
 * @author DEll
 */
public class Principal extends javax.swing.JFrame {

    Archivo arch;
    ConchinitoDigital cochi;
    Usuario usuario;
    String[] arrSeparar;
    Date fecha;
    SimpleDateFormat formato;
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);// centrar  
        arch =new Archivo();//objeto tipo archivo
        cochi=new ConchinitoDigital(); //objeto de tipo cochinito digital
        usuario= new Usuario();

        //FECHA
        fecha= new Date();
        formato = new SimpleDateFormat("dd/MM/YYYY");
        //LLAMADO DE METODOS
        ActualizacionInicial();
        DeshabilitarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPeso = new javax.swing.JTextField();
        jTextFieldDosPesos = new javax.swing.JTextField();
        jTextFieldDiesPesos = new javax.swing.JTextField();
        jTextFieldCincoPesos = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldMonedaAgregada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonAgregarMonedas = new javax.swing.JButton();
        jButtonNuevaAlcancia = new javax.swing.JButton();
        jButtonPeso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonDiesPesos = new javax.swing.JButton();
        jButtonCincoPesos = new javax.swing.JButton();
        jButtonDosPesos = new javax.swing.JButton();
        jButtonCincuenta = new javax.swing.JButton();
        jTextFieldCincuenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTotalDinero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldPeso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextFieldDosPesos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextFieldDiesPesos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextFieldCincoPesos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextFieldFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextFieldNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextFieldMonedaAgregada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/martillo.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jButtonAgregarMonedas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAgregarMonedas.setText("Agregar Monedas");
        jButtonAgregarMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarMonedasActionPerformed(evt);
            }
        });

        jButtonNuevaAlcancia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonNuevaAlcancia.setText("Nueva Alcancia");
        jButtonNuevaAlcancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaAlcanciaActionPerformed(evt);
            }
        });

        jButtonPeso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/peso.jpg"))); // NOI18N
        jButtonPeso.setText("jButton3");
        jButtonPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cochinito.jpg"))); // NOI18N
        jLabel1.setText("jLabelImagenPuerco");

        jButtonDiesPesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dies.jpg"))); // NOI18N
        jButtonDiesPesos.setText("jButton3");
        jButtonDiesPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiesPesosActionPerformed(evt);
            }
        });

        jButtonCincoPesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cinco.jpg"))); // NOI18N
        jButtonCincoPesos.setText("jButton3");
        jButtonCincoPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCincoPesosActionPerformed(evt);
            }
        });

        jButtonDosPesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dos.jpg"))); // NOI18N
        jButtonDosPesos.setText("jButton3");
        jButtonDosPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDosPesosActionPerformed(evt);
            }
        });

        jButtonCincuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cincuenta.jpg"))); // NOI18N
        jButtonCincuenta.setText("jButton3");
        jButtonCincuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCincuentaActionPerformed(evt);
            }
        });

        jTextFieldCincuenta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Fecha inicio:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Propietario:");

        jTextFieldTotalDinero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Alcancia");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Romper Alcancia");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Monedas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonNuevaAlcancia)
                .addGap(395, 395, 395))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonCincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jButtonPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jButtonDosPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldCincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(jTextFieldDosPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jTextFieldCincoPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(jTextFieldDiesPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonCincoPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jButtonDiesPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73)
                                        .addComponent(jButtonAgregarMonedas))
                                    .addComponent(jLabel6)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMonedaAgregada, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(jTextFieldTotalDinero))
                        .addGap(309, 309, 309)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDosPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCincoPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDiesPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButtonAgregarMonedas)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldCincuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldDosPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCincoPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldDiesPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldMonedaAgregada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTotalDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(58, 58, 58)))
                .addComponent(jButtonNuevaAlcancia)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarMonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarMonedasActionPerformed
       
        if(arch.lecturaBolean()){
        jButtonCincuenta.setEnabled(true);
        jButtonPeso.setEnabled(true);
        jButtonDosPesos.setEnabled(true);
        jButtonCincoPesos.setEnabled(true);
        jButtonDiesPesos.setEnabled(true);
        }
       
    }//GEN-LAST:event_jButtonAgregarMonedasActionPerformed

    private void jButtonNuevaAlcanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaAlcanciaActionPerformed
        String nombre;
        String appPa;
        if(arch.lecturaBolean())JOptionPane.showMessageDialog(null,"Cantidad antigua de la cancia: "+cochi.CalcularTotalAhorrado());
        nombre=JOptionPane.showInputDialog("Ingrese su nombre: ");
        appPa=JOptionPane.showInputDialog("Ingrese su apellido Paterno: ");
        if(nombre==null&&appPa==null){// si se Cierra y no se ingresa nada en el JoptionPane
         nombre="NOMBRE";
         appPa="APELLIDO PATERNO";
        }else if(nombre==null)
        nombre="NOMBRE";
        else if(appPa==null)
        appPa="APELLIDO PATERNO";

        usuario.setNombre(nombre);
        usuario.setAppPaterno(appPa);
        cochi.NuevaAlcancia(usuario);
        cochi.setFechaInicio(formato.format(fecha).toString());
        arch.escritura(cochi);
        ActualizacionInicial();
        DeshabilitarBotones();
        jTextFieldMonedaAgregada.setText("Alcancia vacia");
    }//GEN-LAST:event_jButtonNuevaAlcanciaActionPerformed
    //botones
    private void jButtonPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesoActionPerformed
        arrSeparar = arch.lectura().split(",");
        cochi.setPeso(Integer.parseUnsignedInt(arrSeparar[1])+1);
        arch.escritura(cochi);
        ActualizarInterface();
        DeshabilitarBotones();
        jTextFieldMonedaAgregada.setText("Se agrego 1 peso a la alcancia");//actualizar moneda agregada
    }//GEN-LAST:event_jButtonPesoActionPerformed

    private void jButtonDiesPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiesPesosActionPerformed
        arrSeparar = arch.lectura().split(",");
        cochi.setDiesPesos(Integer.parseUnsignedInt(arrSeparar[4])+1);
        arch.escritura(cochi);
        ActualizarInterface();
        DeshabilitarBotones();
        jTextFieldMonedaAgregada.setText("Se agrego 10 pesos a la alcancia");
    }//GEN-LAST:event_jButtonDiesPesosActionPerformed

    private void jButtonCincoPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCincoPesosActionPerformed
        arrSeparar = arch.lectura().split(",");
        cochi.setCincoPesos(Integer.parseUnsignedInt(arrSeparar[3])+1);
        arch.escritura(cochi);
        ActualizarInterface();
        DeshabilitarBotones();
        jTextFieldMonedaAgregada.setText("Se agrego 5 pesos a la alcancia");
    }//GEN-LAST:event_jButtonCincoPesosActionPerformed

    private void jButtonDosPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDosPesosActionPerformed
        arrSeparar = arch.lectura().split(",");
        cochi.setDosPesos(Integer.parseUnsignedInt(arrSeparar[2])+1);
        arch.escritura(cochi);
        ActualizarInterface();
        DeshabilitarBotones();
        jTextFieldMonedaAgregada.setText("Se agrego 2 pesos a la alcancia");
    }//GEN-LAST:event_jButtonDosPesosActionPerformed

    private void jButtonCincuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCincuentaActionPerformed
        arrSeparar = arch.lectura().split(",");
        cochi.setCincuentaCentavos(Integer.parseUnsignedInt(arrSeparar[0])+1);
        arch.escritura(cochi);
        ActualizarInterface();
        DeshabilitarBotones();
        jTextFieldMonedaAgregada.setText("Se agrego 0.50 centavos a la alcancia");
    }//GEN-LAST:event_jButtonCincuentaActionPerformed

    
     public void DeshabilitarBotones(){
        jButtonCincuenta.setEnabled(false);
        jButtonPeso.setEnabled(false);
        jButtonDosPesos.setEnabled(false);
        jButtonCincoPesos.setEnabled(false);
        jButtonDiesPesos.setEnabled(false);
    }
     
     public void ActualizacionInicial(){
     arrSeparar = arch.lectura().split(",");
    
    if(arrSeparar.length==8){
        
    cochi.setCincuentaCentavos(Integer.parseUnsignedInt(arrSeparar[0]));
    cochi.setPeso(Integer.parseUnsignedInt(arrSeparar[1]));
    cochi.setDosPesos(Integer.parseUnsignedInt(arrSeparar[2]));
    cochi.setCincoPesos(Integer.parseUnsignedInt(arrSeparar[3]));
    cochi.setDiesPesos(Integer.parseUnsignedInt(arrSeparar[4]));
    usuario.setNombre(arrSeparar[5]);
    usuario.setAppPaterno(arrSeparar[6]);
    cochi.setFechaInicio(arrSeparar[7]);
    cochi.GuardarPropietario(usuario);
    ActualizarInterface();
    }
    
    }
   
   public void ActualizarInterface(){
     // arrSeparar = arch.lectura().split(",");
      jTextFieldCincuenta.setText(arrSeparar[0]);
      jTextFieldPeso.setText(arrSeparar[1]);
      jTextFieldDosPesos.setText(arrSeparar[2]);
      jTextFieldCincoPesos.setText(arrSeparar[3]);
      jTextFieldDiesPesos.setText(arrSeparar[4]);
      jTextFieldNombre.setText(arrSeparar[5]+" "+arrSeparar[6]);
      jTextFieldFecha.setText(arrSeparar[7]);
      jTextFieldTotalDinero.setText("En la Alcancia hay "+cochi.CalcularTotalAhorrado()+" pesos");
      
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarMonedas;
    private javax.swing.JButton jButtonCincoPesos;
    private javax.swing.JButton jButtonCincuenta;
    private javax.swing.JButton jButtonDiesPesos;
    private javax.swing.JButton jButtonDosPesos;
    private javax.swing.JButton jButtonNuevaAlcancia;
    private javax.swing.JButton jButtonPeso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldCincoPesos;
    private javax.swing.JTextField jTextFieldCincuenta;
    private javax.swing.JTextField jTextFieldDiesPesos;
    private javax.swing.JTextField jTextFieldDosPesos;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldMonedaAgregada;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JTextField jTextFieldTotalDinero;
    // End of variables declaration//GEN-END:variables
}
